# Generated by Django 6.0.1 on 2026-02-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=200)),
                ('entidadpatrocinadora', models.CharField(max_length=200)),
                ('fechafin', models.DateField()),
                ('totalhoras', models.IntegerField()),
                ('descripcioncurso', models.TextField()),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
            ],
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil/'),
        ),
    ]
