# Generated by Django 6.0.1 on 2026-02-01 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_curso_alter_datospersonales_fotoperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AddField(
            model_name='curso',
            name='idcurso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='idcursorealizado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='idperfil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='idexperiencilaboral',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='idproductoacademico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='idproductoslaborales',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='idreconocimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idventagarage',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
