# Generated by Django 6.0.1 on 2026-02-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_curso_id_curso_idcurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='garage/fotos/'),
        ),
    ]
